### ISSUE TITLE
Validation required before usage of eval

### ISSUE THREAD

**Issue by cristianstaicu** [mickyloranger/mongoosify#1]
In file mongoosify.js, the following use of eval is unsafe: 

``` js
var mapPrimitiveTypes = function (primitiveType) {
    if (primitiveType.indexOf('integer') === 0) {
        primitiveType = 'number';
    }
    return eval(primitiveType.charAt(0).toUpperCase() + primitiveType.substr(1));
    ;
};
```

Even though unlikely, this can lead to code execution if for example the json file contains entries like: 

``` js
"type": "string; console.log('my evil code was run')"
```

I suggest refactoring out eval, validate the primitiveType using a regular expression or using a heavyweight sanitization package like: 
https://www.npmjs.com/package/eval-sanitizer

**Comment by nanachimi** [comment]
Thanks cristianstaicu. I will fix that in the next days. But feel free also to provide a fix. I will prefer your first suggestion otherwise i will have a dependency.
